language: generic
sudo: required
services:
  - docker

# Build dev image
before_install:
  - docker build -t danielmacgregor/react-test -f ./client/Dockerfile.dev ./client

# Run unit tests in dev image
script:
  - docker run -e CI=true danielmacgregor/react-test npm test

# Dev build with unit tests succeeded so build production images
after_success:
  - docker build -t danielmacgregor/training-docker-client ./client
  - docker build -t danielmacgregor/training-docker-nginx ./nginx
  - docker build -t danielmacgregor/training-docker-server ./server
  - docker build -t danielmacgregor/training-docker-worker ./worker

  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the built images and push to Docker Hub
  - docker push danielmacgregor/training-docker-client
  - docker push danielmacgregor/training-docker-nginx
  - docker push danielmacgregor/training-docker-server
  - docker push danielmacgregor/training-docker-worker